return {
  ["workshop-1918927570"]={
    configuration_options={
      [""]=0,
      Gameplay=0,
      Vote=0,
      changablefemusic=true,
      fixed_gamemode=false,
      forceendmatch=false,
      gamemode=true,
      gamemodesign=false,
      kick=true,
      newsoil=false,
      perks=true,
      specialevents=false 
    },
    enabled=true 
  } 
}